config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, skip: :registrations
  resources :orders do
    member do
      patch :checkout
    end
  end

  namespace :admin do
    resources :products, except: [ :show ]
    resources :categories, except: [ :show ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_one_attached :image, dependent: :purge_later do |attachable|
    attachable.variant :thumb, resize_to_limit: [ 300, 300 ]
    attachable.variant :detail, resize_to_limit: [ 1080, 1080 ]
  end
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  after_commit :resize_image, on: :create

  private

  def resize_image
    return unless image.attached?

    # Resize the image to 1080x1080 before storing
    image.variant(resize_to_limit: [ 1080, 1080 ]).processed
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  layout "admin"

  def index
    @parent_categories = Category.where(parent_id: nil).where.not(name: DUMP_CATEGORY)
    @child_categories = child_categories
    @dump_category = Category.find_by(name: DUMP_CATEGORY)
    @products_count = Product.count
    @new_product = Product.new
  end

  def new
    @categories = Category.all
    @new_product = Product.new
    render partial: "form", locals: { product: @new_product, child_categories: child_categories, heading: "Tạo sản phẩm mới", url: admin_products_path }
  end

  def create
    if !Category.find(product_params[:category_id]).parent.present?
      flash[:error] = "Danh mục không hợp lệ"
      redirect_to admin_products_path
      return
    end

    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Tạo thành công"
    else
      # flash[:error] = "Lỗi khi tạo sản phẩm"
      flash[:error] = @product.errors.full_messages.join(", ")
    end
    redirect_to admin_products_path
  end

  def edit
    @product = Product.find(params[:id])
    @categories = Category.all
    render partial: "form", locals: { product: @product, child_categories: child_categories, heading: "Chỉnh sửa sản phẩm", url: admin_product_path(@product) }
  end

  def update
    if !Category.find(product_params[:category_id]).parent.present?
      flash[:error] = "Danh mục không hợp lệ"
      redirect_to admin_products_path
      return
    end

    @product = Product.find(params[:id])
    # Check if a new image is being uploaded
    if params[:product][:image].present?
      # Purge the old image if one exists
      @product.image.purge if @product.image.attached?
    end

    if @product.update(product_params)
      flash[:success] = "Chỉnh sửa thành công"
    else
      flash[:error] = "Lỗi khi tạo sản phẩm"
    end
    redirect_to admin_products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @dump_category = Category.find_by(name: DUMP_CATEGORY)
    if @product.update(category: @dump_category)
      flash[:success] = "Xóa thành công"
    else
      flash[:error] = "Lỗi khi xóa sản phẩm"
    end
    redirect_to admin_products_path
  end

  # def destroy
  #   @product = Product.find(params[:id])
  #   if params[:product][:image].present?
  #     # Purge the old image if one exists
  #     @product.image.purge if @product.image.attached?
  #   end
  #
  #   @product.destroy
  #   redirect_to admin_products_path
  # end

  private

  def product_params
    permitted_params = params.require(:product).permit(:name, :description, :price, :category_id, :image)
    permitted_params.delete(:image) if permitted_params[:image].blank?
    permitted_params
  end

  def child_categories
    Category.where.not(parent_id: nil)
  end
end

app/views/admin/products/_form.html.erb
<%= form_with model: product, url: url, data: { admin_target: 'form' }, class: "flex flex-col justify-between" do |f| %>
  <div class="p-[var(--primary-gap)]">
    <h3><%= heading %></h3>
    <div class="field" >
      <% if product.image.attached? %>
        <%= image_tag product.image, class: 'w-full object-cover aspect-square' %>
      <% end %>
    </div>

    <div class="field" >
      <%= f.label :image, "Ảnh sản phẩm" %>
      <%= f.file_field :image %>
    </div>
    <div class="field">
      <%= f.label :name, "Tên sản phẩm" %>
      <%= f.text_field :name, autocomplete: 'off' %>
    </div>

    <div class="field">
      <%= f.label :price, "Giá" %>
      <%= f.number_field :price %>
    </div>

    <div class="field">
      <%= f.label :category_id, "Danh mục sản phẩm" %>
      <%= f.collection_select :category_id, child_categories, :id, :name, { include_blank: true }, { class: 'form-select' } %>
    </div>
  </div>

  <div class="actions mt-8">
    <%= f.submit "Xác nhận" %>
  </div>
<% end %>

app/views/admin/products/_product_card.erb
<div class='flex justify-between items-center py-[var(--primary-gap)]'>
  <div class='flex items-center'>
    <% if product.image.attached? %>
      <%= image_tag product.image.variant(:thumb), class: 'w-20 object-cover' %>
    <% else %>
      <p>No image available</p>
    <% end %>
    <div class='flex flex-col ml-4'>
      <h2><%= product.name %></h2>
      <p><%= number_with_delimiter(product.price.to_i, delimiter: ",") %> ₫</p>
    </div>
  </div>

  <div class='flex items-center gap-4'>
    <button type="button" data-action='admin#getForm' data-url='<%= edit_admin_product_path(product) %>' class= "hover:underline"> Chỉnh sửa </button>
    <%= button_to 'Xoá', admin_product_path(product), method: :delete, class: "text-red-500 hover:underline", data: { confirm: 'bạn chắc chắn muốn xoá?' } %>
  </div>
</div>

app/views/admin/products/_section.html.erb
<div class='mb-4 w-full'>
  <div class="mb-[var(--primary-gap)]">
    <h3 class='text-center'> <%= category.name %> </h3>
  </div>

  <% product_container_class = "flex flex-col divide-y divide-gray-200" %>

  <div class="<%= product_container_class %>">
    <% category.products.each do |product| %>
      <%= render 'product_card', product: product %>
    <% end %>
  </div>

  <% category.children.each do |child| %>
    <div class="border-gray-200 mb-[var(--primary-gap)]">
      <h4 class='font-semibold text-xl'> <%= child.name %> </h4>
    </div>

    <div class="<%= product_container_class %>">
      <% child.products.each do |product| %>
        <%= render 'product_card', product: product %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/admin/products/index.html.erb
<% content_for :main_content do %>
  <div class='py-4 px-10 border-r-2 border-gray-100 flex-1 h-full'>
    <h2 class='text-4xl!'>Sản phẩm</h2>
    <div class='flex justify-between items-center'>
      <p>Tổng cộng <%= @products_count %> sản phẩm </p>
      <button type="button" data-action='click->admin#getForm' data-url='<%= new_admin_product_path %>'>Thêm sản phẩm</button>
    </div>

    <div class="rounded-md mt-4 flex flex-col">
      <% @parent_categories.each do |category| %>
        <%= render 'section', category: category %>
      <% end %>
      <%= render 'section', category: @dump_category %>
    </div>
  </div>
<% end %>
<% content_for :form_section do %>
  <%= render 'form', product: @new_product, child_categories: @child_categories, heading: "Tạo sản phẩm mới", url: admin_products_path %>
<% end %>