config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  devise_for :users, skip: :registrations
  resources :orders do
    member do
      patch :checkout
    end
  end

  namespace :admin do
    resources :products, except: [ :show ]
    resources :categories, except: [ :show ]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/views/layouts/admin.html.erb
<% content_for :page_layout do %>
  <%= render 'shared/navbar' %>
  <main class='flex flex-1 gap-[var(--primary-gap)]' data-controller="admin">
    <div id="admin_sidebar" class=" p-4 bg-white w-[15vw] flex flex-col gap-[var(--primary-gap)]">
      <% link_class = "p-[var(--primary-gap)] font-normal border-1 border-gray-100 rounded-md hover:border-blue-500 hover:text-white! hover:bg-blue-500" %>
      <% link_class_active = "border-blue-500! text-white! bg-blue-500" %>
      <%= active_link_to "Sản phẩm", admin_products_path, class: link_class, active_class: link_class_active %>
      <%= active_link_to "Danh mục", admin_categories_path, class: link_class, active_class: link_class_active %>
    </div>
    <section class="mr-[var(--right-section-width)] bg-white flex-[3]">
      <%= yield :main_content %>
    </section>
    <section class="fixed top-[var(--top-height)] bottom-0 right-0  w-[var(--right-section-width)] bg-white flex-1" data-admin-target="form">
      <%= yield :form_section %>
    </section>
  </main>
<% end %>

<%= render template: 'layouts/application' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Store Management App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="flex flex-col" >
    <% flash.each do |type, message| %>
      <% flash_classes = { notice: "bg-blue-500", error: "bg-red-500", success: "bg-green-500" } %>
      <div id="flash-message" class="fixed top-5 left-1/2 z-[999] -translate-x-1/2 px-4 py-2 <%= flash_classes[type.to_sym] %> text-black rounded-lg shadow-lg">
        <%= message %>
      </div>
      <script>
        setTimeout(() => {
          document.getElementById('flash-message')?.remove();
        }, 5000);
      </script>
    <% end %>

    <% if content_for?(:page_layout) %>
      <%= yield(:page_layout) %>
    <% else %>
      <%= render "shared/navbar" %>
      <main class="flex-grow flex flex-col w-full">
        <%= yield %>
      </main>
    <% end %>


  </body>
</html>